import prisma from '../../config/db.js';
import { nextAvailable } from '../doctor-appointments/doctor-appointments.service.js';
import { recordAudit } from '../audit/audit.service.js';
// Who the doctor behind a profile is, for the other side of an Activity log entry.
const doctorUserId=async(tx,doctorProfileId)=>(await tx.professionalProfile.findUnique({where:{id:doctorProfileId},select:{userId:true}}))?.userId??null;
const doc={id:true,professionType:true,specialty:true,practiceName:true,verificationStatus:true,bio:true,yearsOfExperience:true,consultationFeeMinor:true,consultationTypes:true,practiceAddress:true,user:{select:{full_name:true}}};
// Directory entries also carry the earliest open booking slot (null when none is published).
const withNext=async(items)=>{const next=await nextAvailable(items.map((d)=>d.id));return items.map((d)=>({...d,nextAvailableAt:next.get(d.id)??null}));}; const rel={id:true,patientId:true,doctorProfileId:true,status:true,requestedAt:true,respondedAt:true,revokedAt:true,doctorProfile:{select:doc}};
const error=(code)=>Object.assign(new Error(code),{code}); const audit=(tx,userId,type,id)=>tx.activityLog.create({data:{userId,type,description:'Doctor care relationship changed',meta:{relationshipId:id}}});
const verifiedDoctor=(tx,id)=>tx.professionalProfile.findFirst({where:{id,professionType:'DOCTOR',verificationStatus:'VERIFIED'},select:{id:true}});
const patientRole=(tx,userId)=>tx.userRole.findFirst({where:{userId,role:'PATIENT'},select:{id:true}});
export const doctors=async(q)=>{const where={professionType:'DOCTOR',verificationStatus:'VERIFIED',...(q.specialty?{specialty:{equals:q.specialty,mode:'insensitive'}}:{}),...(q.search?{OR:[{specialty:{contains:q.search,mode:'insensitive'}},{user:{full_name:{contains:q.search,mode:'insensitive'}}}]}:{})};const[items,total]=await Promise.all([prisma.professionalProfile.findMany({where,select:doc,orderBy:{createdAt:'asc'},skip:(q.page-1)*q.limit,take:q.limit}),prisma.professionalProfile.count({where})]);return{items:await withNext(items),page:q.page,limit:q.limit,total};};
export const doctor=async(id)=>{const d=await prisma.professionalProfile.findFirst({where:{id,professionType:'DOCTOR',verificationStatus:'VERIFIED'},select:doc});return d?(await withNext([d]))[0]:null;};
export const request= (patientId,doctorProfileId)=>prisma.$transaction(async tx=>{if(!await patientRole(tx,patientId)||!await verifiedDoctor(tx,doctorProfileId))throw error('NOT_FOUND');const existing=await tx.doctorCareRelationship.findFirst({where:{patientId,doctorProfileId},select:{id:true,status:true}});if(existing)throw error('DUPLICATE');const item=await tx.doctorCareRelationship.create({data:{patientId,doctorProfileId},select:rel});await audit(tx,patientId,'DOCTOR_CARE_REQUESTED',item.id);await recordAudit(tx,{actorUserId:patientId,subjectUserId:patientId,relatedUserId:await doctorUserId(tx,doctorProfileId),action:'CARE_REQUESTED',resourceType:'care_relationship',resourceId:item.id});return item;});
export const patientList=(patientId)=>prisma.doctorCareRelationship.findMany({where:{patientId},select:rel,orderBy:{requestedAt:'desc'}});
const doctorProfile=(tx,userId)=>tx.professionalProfile.findFirst({where:{userId,professionType:'DOCTOR',verificationStatus:'VERIFIED'},select:{id:true}});
export const doctorList=(userId)=>prisma.doctorCareRelationship.findMany({where:{doctorProfile:{userId,professionType:'DOCTOR',verificationStatus:'VERIFIED'}},select:{id:true,status:true,requestedAt:true,respondedAt:true,revokedAt:true,patientId:true},orderBy:{requestedAt:'desc'}});
export const respond=(userId,id,status)=>prisma.$transaction(async tx=>{const d=await doctorProfile(tx,userId);if(!d)throw error('NOT_FOUND');const result=await tx.doctorCareRelationship.updateMany({where:{id,doctorProfileId:d.id,status:'PENDING'},data:{status,respondedAt:new Date()}});if(!result.count)throw error('NOT_FOUND');const item=await tx.doctorCareRelationship.findFirst({where:{id,doctorProfileId:d.id},select:rel});await audit(tx,userId,`DOCTOR_CARE_${status}`,id);await recordAudit(tx,{actorUserId:userId,subjectUserId:item.patientId,action:status==='ACTIVE'?'CARE_ACCEPTED':'CARE_DECLINED',resourceType:'care_relationship',resourceId:id});return item;});
export const revoke=(patientId,id)=>prisma.$transaction(async tx=>{if(!await patientRole(tx,patientId))throw error('NOT_FOUND');const result=await tx.doctorCareRelationship.updateMany({where:{id,patientId,status:'ACTIVE'},data:{status:'REVOKED',revokedAt:new Date()}});if(!result.count)throw error('NOT_FOUND');await audit(tx,patientId,'DOCTOR_CARE_REVOKED',id);const relation=await tx.doctorCareRelationship.findFirst({where:{id,patientId},select:{doctorProfileId:true}});await recordAudit(tx,{actorUserId:patientId,subjectUserId:patientId,relatedUserId:relation?await doctorUserId(tx,relation.doctorProfileId):null,action:'CARE_REVOKED',resourceType:'care_relationship',resourceId:id});});
