import express from 'express'; import jwt from 'jsonwebtoken'; import request from 'supertest'; import { beforeEach, describe, expect, it, vi } from 'vitest';
const fn = () => vi.fn(); const sent = vi.fn();
const tx = { userRole: { findFirst: fn() }, user: { findUnique: fn() }, careRelationship: { findFirst: fn(), create: fn(), update: fn(), updateMany: fn() }, activityLog: { create: fn() } };
const prisma = { user: { findUnique: fn() }, careRelationship: { findMany: fn(), count: fn(), findFirst: fn() }, $transaction: fn() };
vi.mock('../src/config/db.js', () => ({ default: prisma })); vi.mock('../src/modules/family-care/family-care.email.js', () => ({ sendCaregiverInvite: sent }));
const { default: routes } = await import('../src/modules/family-care/family-care.routes.js'); process.env.JWT_SECRET = 'family-test-secret'; const patientId = '5f95ea6b-15e7-4b29-85be-8189931bf2d6'; const caregiverId = '4b95ea6b-15e7-4b29-85be-8189931bf2d6'; const auth = (id) => ({ Authorization: `Bearer ${jwt.sign({ userId: id }, process.env.JWT_SECRET)}` }); const app = express(); app.use(express.json()); app.use('/family-care', routes); const token = 'a'.repeat(64); const invite = { email: 'care@example.test', relationshipType: 'CAREGIVER', permissions: ['RECORDS', 'VITALS'] };
beforeEach(() => { vi.clearAllMocks(); tx.userRole.findFirst.mockResolvedValue({ id: 'patient-role' }); prisma.$transaction.mockImplementation((work) => work(tx)); prisma.user.findUnique.mockResolvedValue({ email: 'patient@example.test' }); prisma.careRelationship.findMany.mockResolvedValue([]); prisma.careRelationship.count.mockResolvedValue(0); prisma.careRelationship.findFirst.mockResolvedValue(null); tx.user.findUnique.mockResolvedValue({ email: 'care@example.test' }); tx.careRelationship.findFirst.mockResolvedValue(null); tx.careRelationship.create.mockResolvedValue({ id: patientId, patientId, caregiverEmail: invite.email, relationshipType: 'CAREGIVER', permissions: invite.permissions, status: 'PENDING' }); tx.careRelationship.update.mockResolvedValue({ id: patientId, caregiverId, status: 'ACTIVE', permissions: invite.permissions }); tx.careRelationship.updateMany.mockResolvedValue({ count: 1 }); tx.activityLog.create.mockResolvedValue({}); sent.mockResolvedValue({ delivered: false }); });
describe('family care routes', () => {
  it('returns patient/caregiver scoped empty relationship lists and creates a hashed-token invitation', async () => { const empty = await request(app).get('/family-care?page=2&limit=5').set(auth(patientId)); expect(empty.status).toBe(200); expect(empty.body.data).toMatchObject({ items: [], page: 2, limit: 5, total: 0 }); expect(prisma.careRelationship.findMany).toHaveBeenCalledWith(expect.objectContaining({ where: expect.objectContaining({ OR: expect.arrayContaining([{ patientId }]) }) })); const response = await request(app).post('/family-care/invitations').set(auth(patientId)).send(invite); expect(response.status).toBe(201); expect(response.body.data).not.toHaveProperty('token'); expect(tx.careRelationship.create.mock.calls[0][0].data.invitationTokenHash).not.toEqual(expect.stringContaining('care@example')); expect(sent).toHaveBeenCalledWith(expect.objectContaining({ email: invite.email, token: expect.any(String) })); });
  it('accepts and declines only a matching pending invitation and does not retain raw tokens', async () => { tx.careRelationship.findFirst.mockResolvedValue({ id: patientId, caregiverEmail: invite.email, status: 'PENDING', expiresAt: new Date(Date.now() + 60000), permissions: invite.permissions }); expect((await request(app).post('/family-care/invitations/accept').set(auth(caregiverId)).send({ token })).status).toBe(200); expect(JSON.stringify(tx.careRelationship.findFirst.mock.calls)).not.toContain(token); tx.careRelationship.findFirst.mockResolvedValueOnce({ id: patientId, caregiverEmail: invite.email, status: 'PENDING', expiresAt: new Date(Date.now() + 60000), permissions: [] }); expect((await request(app).post('/family-care/invitations/decline').set(auth(caregiverId)).send({ token })).status).toBe(200); });
  it('denies expired, invalid, duplicate, and cross-user relationship transitions safely', async () => { tx.careRelationship.findFirst.mockResolvedValueOnce({ id: patientId, caregiverEmail: invite.email, status: 'PENDING', expiresAt: new Date(Date.now() - 1), permissions: [] }); expect((await request(app).post('/family-care/invitations/accept').set(auth(caregiverId)).send({ token })).status).toBe(410); tx.careRelationship.findFirst.mockResolvedValue(null); expect((await request(app).post('/family-care/invitations/accept').set(auth(caregiverId)).send({ token })).body).toEqual({ status: 'error', message: 'Relationship not found' }); tx.careRelationship.findFirst.mockResolvedValueOnce({ id: patientId }); expect((await request(app).post('/family-care/invitations').set(auth(patientId)).send(invite)).status).toBe(409); tx.careRelationship.updateMany.mockResolvedValue({ count: 0 }); expect((await request(app).patch(`/family-care/${caregiverId}/permissions`).set(auth(patientId)).send({ permissions: ['RECORDS'] })).status).toBe(404); });
  it('returns only active caregiver permissions and rejects malformed data or tokens', async () => { prisma.careRelationship.findFirst.mockResolvedValueOnce({ permissions: ['VITALS'] }); expect((await request(app).get(`/family-care/access/${patientId}`).set(auth(caregiverId))).body.data).toEqual({ permissions: ['VITALS'] }); prisma.careRelationship.findFirst.mockResolvedValueOnce(null); expect((await request(app).get(`/family-care/access/${patientId}`).set(auth(caregiverId))).body.data).toEqual({ permissions: [] }); expect((await request(app).post('/family-care/invitations').set(auth(patientId)).send({ ...invite, permissions: ['PAYMENTS'] })).status).toBe(400); expect((await request(app).post('/family-care/invitations/accept').set(auth(caregiverId)).send({ token: 'short' })).status).toBe(400); expect((await request(app).get('/family-care/not-valid')).status).toBe(401); expect((await request(app).get('/family-care').set('Authorization', 'Bearer bad')).status).toBe(401); const expired = jwt.sign({ userId: patientId }, process.env.JWT_SECRET, { expiresIn: -1 }); expect((await request(app).get('/family-care').set('Authorization', `Bearer ${expired}`)).status).toBe(401); });
  it('hides database failures', async () => { prisma.user.findUnique.mockRejectedValueOnce(new Error('db-secret')); const response = await request(app).get('/family-care').set(auth(patientId)); expect(response.status).toBe(500); expect(response.body.message).toBe('Family care module temporarily unavailable'); });
});
