import express from 'express'; import jwt from 'jsonwebtoken'; import request from 'supertest'; import { beforeEach, describe, expect, it, vi } from 'vitest';
const fn = () => vi.fn();
const tx = { category: { findFirst: fn(), create: fn(), updateMany: fn(), delete: fn() }, medicalRecord: { create: fn(), updateMany: fn(), findFirst: fn(), deleteMany: fn(), count: fn() }, activityLog: { create: fn() } };
const prisma = { medicalRecord: { findMany: fn(), count: fn(), findFirst: fn(), groupBy: fn() }, category: { findMany: fn() }, userProfile: { findUnique: fn() }, $transaction: fn() };
vi.mock('../src/config/db.js', () => ({ default: prisma }));
const { default: routes } = await import('../src/modules/medical-records/medical-records.routes.js');
process.env.JWT_SECRET = 'records-test-secret'; const userId = '5f95ea6b-15e7-4b29-85be-8189931bf2d6'; const otherId = '4b95ea6b-15e7-4b29-85be-8189931bf2d6'; const auth = { Authorization: `Bearer ${jwt.sign({ userId }, process.env.JWT_SECRET)}` }; const app = express(); app.use(express.json()); app.use('/medical-records', routes);
const record = { title: 'Blood test', recordType: 'LAB_RESULT', date: '2026-09-11T09:00:00.000Z', facility: 'Clinic', documentUrl: 'https://example.test/metadata.pdf' };
beforeEach(() => { vi.clearAllMocks(); prisma.$transaction.mockImplementation((work) => work(tx)); prisma.medicalRecord.findMany.mockResolvedValue([]); prisma.medicalRecord.count.mockResolvedValue(0); prisma.medicalRecord.findFirst.mockResolvedValue(null); prisma.medicalRecord.groupBy.mockResolvedValue([]); prisma.category.findMany.mockResolvedValue([]); prisma.userProfile.findUnique.mockResolvedValue(null); tx.category.findFirst.mockResolvedValue({ id: userId }); tx.category.create.mockResolvedValue({ id: userId, name: 'Labs', icon: 'flask', isDefault: false }); tx.category.updateMany.mockResolvedValue({ count: 1 }); tx.category.delete.mockResolvedValue({}); tx.medicalRecord.create.mockResolvedValue({ id: userId, ...record }); tx.medicalRecord.updateMany.mockResolvedValue({ count: 1 }); tx.medicalRecord.findFirst.mockResolvedValue({ id: userId, ...record }); tx.medicalRecord.deleteMany.mockResolvedValue({ count: 1 }); tx.medicalRecord.count.mockResolvedValue(0); tx.activityLog.create.mockResolvedValue({}); });
describe('medical records routes', () => {
  it('returns scoped empty timeline, filters, uncategorized rows, and category counts', async () => { const response = await request(app).get('/medical-records/timeline?page=2&limit=5&type=LAB_RESULT&search=blood&from=2026-09-01T00:00:00.000Z&to=2026-09-30T00:00:00.000Z&sort=asc').set(auth); expect(response.status).toBe(200); expect(response.body.data).toMatchObject({ items: [], page: 2, limit: 5, total: 0 }); expect(prisma.medicalRecord.findMany).toHaveBeenCalledWith(expect.objectContaining({ where: expect.objectContaining({ userId, recordType: 'LAB_RESULT' }), orderBy: { date: 'asc' }, skip: 5, take: 5 })); await request(app).get('/medical-records/uncategorized').set(auth); expect(prisma.medicalRecord.findMany).toHaveBeenLastCalledWith(expect.objectContaining({ where: { userId, categoryId: null } })); expect((await request(app).get('/medical-records/categories/counts').set(auth)).status).toBe(200); expect(prisma.medicalRecord.groupBy).toHaveBeenCalledWith(expect.objectContaining({ where: { userId } })); });
  it('creates, updates, assigns/removes categories and logs only identifiers', async () => { expect((await request(app).post('/medical-records').set(auth).send(record)).status).toBe(201); expect((await request(app).patch(`/medical-records/${userId}`).set(auth).send({ title: 'Updated' })).status).toBe(200); expect((await request(app).patch(`/medical-records/${userId}/category`).set(auth).send({ categoryId: userId })).status).toBe(200); expect((await request(app).patch(`/medical-records/${userId}/category`).set(auth).send({ categoryId: null })).status).toBe(200); expect(JSON.stringify(tx.activityLog.create.mock.calls)).not.toContain('Blood test'); });
  it('handles categories, blocks deletion while records exist, then permits deletion after removal', async () => { expect((await request(app).post('/medical-records/categories').set(auth).send({ name: 'Labs', icon: 'flask' })).status).toBe(201); tx.medicalRecord.count.mockResolvedValueOnce(1); const blocked = await request(app).delete(`/medical-records/categories/${userId}`).set(auth); expect(blocked.status).toBe(409); expect(blocked.body.message).toBe('Category contains records'); tx.medicalRecord.count.mockResolvedValueOnce(0); expect((await request(app).delete(`/medical-records/categories/${userId}`).set(auth)).status).toBe(200); });
  it('uses identical 404s for missing or cross-user record/category access', async () => { prisma.medicalRecord.findFirst.mockResolvedValueOnce(null); const missing = await request(app).get(`/medical-records/${userId}`).set(auth); tx.medicalRecord.updateMany.mockResolvedValue({ count: 0 }); tx.category.findFirst.mockResolvedValue(null); const other = await request(app).patch(`/medical-records/${otherId}`).set(auth).send({ title: 'No' }); const category = await request(app).delete(`/medical-records/categories/${otherId}`).set(auth); expect([missing.body, other.body, category.body]).toEqual([{ status: 'error', message: 'Resource not found' }, { status: 'error', message: 'Resource not found' }, { status: 'error', message: 'Resource not found' }]); });
  it('validates inputs, minimizes emergency data, rejects bad tokens, and hides database failures', async () => { expect((await request(app).post('/medical-records').set(auth).send({ ...record, unknown: true })).status).toBe(400); expect((await request(app).get('/medical-records/not-uuid').set(auth)).status).toBe(400); expect((await request(app).get('/medical-records?from=2026-10-02T00:00:00.000Z&to=2026-10-01T00:00:00.000Z').set(auth)).status).toBe(400); prisma.userProfile.findUnique.mockResolvedValueOnce({ blood_type: 'O+', chronic_conditions: 'Asthma', known_allergies: 'None', emergencyContactName: 'Ada', electronic_health_records: true }); const emergency = await request(app).get('/medical-records/emergency-summary').set(auth); expect(emergency.body.data).not.toHaveProperty('records'); expect(prisma.userProfile.findUnique).toHaveBeenCalledWith(expect.objectContaining({ where: { userId } })); expect((await request(app).get('/medical-records')).status).toBe(401); expect((await request(app).get('/medical-records').set('Authorization', 'Bearer bad')).status).toBe(401); const expired = jwt.sign({ userId }, process.env.JWT_SECRET, { expiresIn: -1 }); expect((await request(app).get('/medical-records').set('Authorization', `Bearer ${expired}`)).status).toBe(401); prisma.medicalRecord.findMany.mockRejectedValueOnce(new Error('db-secret')); const failed = await request(app).get('/medical-records').set(auth); expect(failed.status).toBe(500); expect(failed.body.message).toBe('Medical records module temporarily unavailable'); });
});
