import express from 'express'; import jwt from 'jsonwebtoken'; import request from 'supertest'; import { beforeEach, describe, expect, it, vi } from 'vitest';
const prisma = { notification: { findMany: vi.fn(), count: vi.fn(), updateMany: vi.fn() } };
vi.mock('../src/config/db.js', () => ({ default: prisma }));
const { default: routes } = await import('../src/modules/notifications/notifications.routes.js');
process.env.JWT_SECRET = 'notification-test-secret'; const auth = { Authorization: `Bearer ${jwt.sign({ userId: '5f95ea6b-15e7-4b29-85be-8189931bf2d6' }, process.env.JWT_SECRET)}` }; const app = express(); app.use(express.json()); app.use('/notifications', routes);
beforeEach(() => { vi.clearAllMocks(); prisma.notification.findMany.mockResolvedValue([]); prisma.notification.count.mockResolvedValue(0); prisma.notification.updateMany.mockResolvedValue({ count: 1 }); });
describe('notifications routes', () => {
  it('returns scoped empty states and rejects unauthenticated access', async () => { expect((await request(app).get('/notifications')).status).toBe(401); const response = await request(app).get('/notifications?page=1&limit=20').set(auth); expect(response.status).toBe(200); expect(response.body.data.items).toEqual([]); expect(prisma.notification.findMany).toHaveBeenCalledWith(expect.objectContaining({ where: { userId: '5f95ea6b-15e7-4b29-85be-8189931bf2d6' } })); });
  it('validates pagination and prevents cross-user read updates', async () => { expect((await request(app).get('/notifications?limit=1000').set(auth)).status).toBe(400); prisma.notification.updateMany.mockResolvedValueOnce({ count: 0 }); expect((await request(app).patch('/notifications/5f95ea6b-15e7-4b29-85be-8189931bf2d6/read').set(auth)).status).toBe(404); expect(prisma.notification.updateMany).toHaveBeenCalledWith(expect.objectContaining({ where: { id: '5f95ea6b-15e7-4b29-85be-8189931bf2d6', userId: '5f95ea6b-15e7-4b29-85be-8189931bf2d6' } })); });
  it('marks an owned notification read idempotently and marks all unread notifications', async () => { const id = '5f95ea6b-15e7-4b29-85be-8189931bf2d6'; expect((await request(app).patch(`/notifications/${id}/read`).set(auth)).status).toBe(200); expect((await request(app).patch(`/notifications/${id}/read`).set(auth)).status).toBe(200); expect((await request(app).patch('/notifications/read-all').set(auth)).body.data.updated).toBe(1); expect(prisma.notification.updateMany).toHaveBeenLastCalledWith({ where: { userId: id, isRead: false }, data: { isRead: true } }); });
  it('handles empty read-all, malformed and expired tokens, UUIDs and query enums safely', async () => { prisma.notification.updateMany.mockResolvedValueOnce({ count: 0 }); expect((await request(app).patch('/notifications/read-all').set(auth)).body.data.updated).toBe(0); expect((await request(app).get('/notifications').set('Authorization', 'Bearer bad.token')).status).toBe(401); const expired = jwt.sign({ userId: '5f95ea6b-15e7-4b29-85be-8189931bf2d6' }, process.env.JWT_SECRET, { expiresIn: -1 }); expect((await request(app).get('/notifications').set('Authorization', `Bearer ${expired}`)).status).toBe(401); expect((await request(app).patch('/notifications/not-uuid/read').set(auth)).status).toBe(400); expect((await request(app).get('/notifications?unreadOnly=maybe').set(auth)).status).toBe(400); });
  it('returns pagination metadata, unread filtering and safe database errors', async () => { prisma.notification.findMany.mockResolvedValueOnce([{ id: 'n1' }]); prisma.notification.count.mockResolvedValueOnce(1).mockResolvedValueOnce(3); const response = await request(app).get('/notifications?page=2&limit=5&unreadOnly=true').set(auth); expect(response.body.data).toMatchObject({ page: 2, limit: 5, total: 1, unreadCount: 3 }); expect(prisma.notification.findMany).toHaveBeenCalledWith(expect.objectContaining({ where: { userId: '5f95ea6b-15e7-4b29-85be-8189931bf2d6', isRead: false }, skip: 5, take: 5 })); prisma.notification.findMany.mockRejectedValueOnce(new Error('database secret')); const failed = await request(app).get('/notifications').set(auth); expect(failed.status).toBe(500); expect(failed.body.message).toBe('Notifications module temporarily unavailable'); });
});
