import {beforeEach,describe,it,expect,vi} from 'vitest';
import {capabilities,PORTAL_PROFESSIONS,credentialRequirements} from '../src/modules/professionals/professionCatalog.js';
import {professionalRegistrationSchema} from '../src/modules/doctors/onboarding.validator.js';
import {approvalBlockers} from '../src/modules/doctors/onboarding.policy.js';
import {patientPlan,contentSchema} from '../src/modules/professional-care/care.policy.js';
import {createCareService} from '../src/modules/professional-care/care.service.js';
const structuredClone = globalThis.structuredClone;
const content={title:'Weekly nutrition plan',startsOn:'2026-10-06',endsOn:'2026-10-12',goals:'Balanced meals',history:'PRIVATE intake',preferences:'Local foods',allergies:'None reported',restrictions:'',budget:'',instructions:'Review in one week',activities:'',followUpOn:null,meals:[{day:'Monday',time:'Breakfast',food:'Oats',portion:'Professional-defined serving',alternative:'',preparation:''}],targets:[]};
describe('profession scope and requirements',()=>{
  it.each(PORTAL_PROFESSIONS)('%s approval never grants doctor-only scope by mistake',professionType=>{const c=capabilities({professionType,verificationStatus:'VERIFIED'},{discipline:'DIETITIAN'});expect(c.prescribe).toBe(professionType==='DOCTOR');expect(c.clinicalRecords).toBe(professionType==='DOCTOR');});
  it('nutritionists cannot publish dietitian meal tables and pending dietitians cannot practise',()=>{expect(capabilities({professionType:'NUTRITIONIST_DIETITIAN',verificationStatus:'VERIFIED'},{discipline:'NUTRITIONIST'}).nutrition).toBe(false);expect(capabilities({professionType:'NUTRITIONIST_DIETITIAN',verificationStatus:'PENDING'},{discipline:'DIETITIAN'}).carePlans).toBe(false);});
  it.each(PORTAL_PROFESSIONS.filter(t=>t!=='DOCTOR'))('validates a separate %s discipline and rejects unknown scope',type=>{const discipline={NUTRITIONIST_DIETITIAN:'DIETITIAN',PSYCHOLOGIST:'CLINICAL_PSYCHOLOGIST',COUNSELLOR:'COUNSELLOR',CAREGIVER:'NON_CLINICAL_CAREGIVER',FITNESS_COACH:'FITNESS_COACH',HEALTH_EDUCATOR:'HEALTH_EDUCATOR'}[type];const body={firstName:'Synthetic',lastName:'Professional',email:'synthetic@example.test',phone:'+2348012345678',password:'Synthetic long phrase',professionType:type,discipline,specialty:'Support',qualification:'Reviewed qualification',university:'Institution',graduationYear:2010,yearsOfExperience:5,services:'Professional services',practiceState:'Lagos',city:'Lagos',country:'NG',consentVersion:'professional-registration-v1',declaration:true,termsAccepted:true};expect(professionalRegistrationSchema.safeParse({body}).success).toBe(true);expect(professionalRegistrationSchema.safeParse({body:{...body,discipline:'THERAPIST'}}).success).toBe(false);});
  it('requires dated nursing licensing but not a fabricated generic caregiver licence',()=>{expect(credentialRequirements({professionType:'CAREGIVER',discipline:'REGISTERED_NURSE'}).map(v=>v.kind)).toEqual(['qualification','licence','registrationCertificate']);const details={professionType:'CAREGIVER',discipline:'NON_CLINICAL_CAREGIVER'};const application={details,submittedAt:new Date(),credentials:credentialRequirements(details).map(({kind})=>({id:kind,kind,createdAt:new Date(),scanStatus:'CLEAN',storageBucket:'sabi-hospital-evidence-clean',reviewStatus:'VERIFIED'}))};expect(approvalBlockers({user:{accountStatus:'ACTIVE',emailVerifiedAt:new Date()}},application)).toEqual([]);});
  it('does not fabricate nutrition and rejects unsourced targets or reversed dates',()=>{expect(contentSchema.safeParse(content).success).toBe(true);expect(contentSchema.safeParse({...content,targets:[{name:'Energy',value:'2000 kcal',source:''}]}).success).toBe(false);expect(contentSchema.safeParse({...content,endsOn:'2026-10-01'}).success).toBe(false);});
  it('patient projection exposes only published content, never draft, intake, or notes',()=>{const p=patientPlan({id:'p',professionalId:'pro',kind:'NUTRITION',draft:{title:'PRIVATE DRAFT'},publishedVersion:1,versions:[{number:1,publishedAt:new Date(),content}],notes:[{text:'PRIVATE SESSION'}],feedback:[],professional:{user:{full_name:'Dietitian'}}});expect(p.content.title).toBe(content.title);expect(p.content.history).toBeUndefined();expect(JSON.stringify(p)).not.toMatch(/PRIVATE/);});
});
describe('connected care plan service',()=>{
  let db,service,plan;
  beforeEach(()=>{plan={id:'plan',professionalId:'pro',patientId:'patient',kind:'NUTRITION',title:content.title,draft:structuredClone(content),revision:1,publishedVersion:null,versions:[],feedback:[],notes:[]};db={$queryRaw:vi.fn(),professionalProfile:{findFirst:vi.fn(async()=>({id:'pro',userId:'owner',professionType:'NUTRITIONIST_DIETITIAN',verificationStatus:'VERIFIED',doctorApplication:{details:{discipline:'DIETITIAN'}}})),findUnique:vi.fn(async()=>({userId:'owner'}))},professionalCareConsent:{findFirst:vi.fn(async()=>({id:'consent'}))},professionalCarePlan:{findFirst:vi.fn(async()=>structuredClone(plan)),update:vi.fn(async({data})=>{plan={...plan,...data,revision:plan.revision+1};return structuredClone(plan);})},professionalCareVersion:{create:vi.fn(async({data})=>{plan.versions.push({id:'v'+data.number,...data});return data;})},professionalCareNote:{create:vi.fn(async({data})=>data)},professionalCareFeedback:{create:vi.fn(async({data})=>data)},notification:{create:vi.fn()},activityLog:{create:vi.fn()}};db.$transaction=vi.fn(f=>f(db));service=createCareService(db);});
  it('publishes, revises, and preserves the earlier version',async()=>{await service.publish('owner','plan',1);expect(plan.publishedVersion).toBe(1);await service.save('owner','plan',{revision:2,content:{...content,title:'Revised meals'}});expect(plan.publishedVersion).toBe(1);expect(plan.versions[0].content.title).toBe(content.title);await service.publish('owner','plan',3);expect(plan.versions.map(v=>v.number)).toEqual([1,2]);expect(plan.versions[1].content.title).toBe('Revised meals');expect(db.notification.create).toHaveBeenCalledTimes(2);});
  it('rejects access after consent revocation and makes no writes',async()=>{db.professionalCareConsent.findFirst.mockResolvedValue(null);await expect(service.publish('owner','plan',1)).rejects.toMatchObject({status:403});expect(db.professionalCareVersion.create).not.toHaveBeenCalled();});
  it('scopes every professional plan lookup to the authenticated owner',async()=>{await service.detail('owner','plan');expect(db.professionalCarePlan.findFirst).toHaveBeenCalledWith(expect.objectContaining({where:{id:'plan',professionalId:'pro'}}));db.professionalCarePlan.findFirst.mockResolvedValue(null);await expect(service.detail('other','plan')).rejects.toMatchObject({status:404});});
  it('rejects stale revisions and archived writes',async()=>{await expect(service.publish('owner','plan',2)).rejects.toMatchObject({status:409});plan.archivedAt=new Date();await expect(service.save('owner','plan',{revision:1,content})).rejects.toMatchObject({status:409});expect(db.professionalCarePlan.update).not.toHaveBeenCalled();});
  it('does not let counsellors or nutritionists create meal plans',async()=>{for(const professionType of ['COUNSELLOR','NUTRITIONIST_DIETITIAN']){db.professionalProfile.findFirst.mockResolvedValue({id:'pro',professionType,verificationStatus:'VERIFIED',doctorApplication:{details:{discipline:professionType==='COUNSELLOR'?'COUNSELLOR':'NUTRITIONIST'}}});await expect(service.save('owner','plan',{revision:1,content})).rejects.toMatchObject({status:403});}expect(db.professionalCarePlan.update).not.toHaveBeenCalled();});
  it('locks publishing and stores private notes separately from published versions',async()=>{await service.note('owner','plan',{text:'Session review'});expect(db.$queryRaw).toHaveBeenCalledTimes(2);expect(db.professionalCareVersion.create).not.toHaveBeenCalled();expect(db.professionalCareNote.create).toHaveBeenCalledWith({data:{planId:'plan',text:'Session review',followUpAt:null}});});
  it('does not allow feedback on another patient record or unpublished plan',async()=>{db.professionalCarePlan.findFirst.mockResolvedValue(null);await expect(service.feedback('other','plan',{version:1,message:'test',progress:'ON_TRACK'})).rejects.toMatchObject({status:404});expect(db.professionalCarePlan.findFirst).toHaveBeenCalledWith({where:{id:'plan',patientId:'other',publishedVersion:{not:null}}});expect(db.professionalCareFeedback.create).not.toHaveBeenCalled();});
});
