import express from 'express';
import { z } from 'zod';
import { protect } from '../../middleware/authMiddleware.js';
import { validate } from '../../middleware/validateMiddleware.js';
import { createLimiter } from '../../middleware/rateLimitMiddleware.js';
import { careService as S } from './care.service.js';
import * as V from './care.policy.js';
const router=express.Router();
const params=z.object({params:z.object({id:z.uuid()})});
const wrap=f=>async(req,res,next)=>{res.set('Cache-Control','no-store');try{res.json({data:await f(req)});}catch(e){if(e.status)return res.status(e.status).json({message:e.message});if(e.code==='P2034')return res.status(409).json({message:'Concurrent update. Refresh and retry.'});if(e instanceof z.ZodError)return res.status(400).json({message:'Invalid care plan.',errors:e.issues});next(e);}};
router.get('/directory',wrap(()=>S.directory()));
router.use(protect,createLimiter({kind:'professional-care',max:120}));
router.get('/patient/providers',wrap(r=>S.candidates(r.user.id)));
router.put('/patient/consents/:id',validate(params),validate(V.consentSchema),wrap(r=>S.consent(r.user.id,r.params.id,r.body.active)));
router.get('/patient/plans',wrap(r=>S.patientPlans(r.user.id)));
router.post('/patient/plans/:id/feedback',validate(params),validate(V.feedbackSchema),wrap(r=>S.feedback(r.user.id,r.params.id,r.body)));
router.get('/workspace',wrap(r=>S.workspace(r.user.id)));
router.get('/plans/:id',validate(params),wrap(r=>S.detail(r.user.id,r.params.id)));
router.post('/plans',validate(V.saveSchema),wrap(r=>S.save(r.user.id,null,r.body)));
router.put('/plans/:id',validate(params),validate(V.saveSchema),wrap(r=>S.save(r.user.id,r.params.id,r.body)));
router.post('/plans/:id/publish',validate(params),validate(V.revisionSchema),wrap(r=>S.publish(r.user.id,r.params.id,r.body.revision)));
router.post('/plans/:id/archive',validate(params),validate(V.revisionSchema),wrap(r=>S.archive(r.user.id,r.params.id,r.body.revision)));
router.post('/plans/:id/notes',validate(params),validate(V.noteSchema),wrap(r=>S.note(r.user.id,r.params.id,r.body)));
router.post('/templates',validate(V.templateSchema),wrap(r=>S.template(r.user.id,r.body)));
export default router;
