import { createHash, randomBytes } from 'node:crypto';
import * as adapter from './paystack.adapter.js'; import * as r from './payments.repository.js';
const fail=(code)=>Object.assign(new Error(code),{code});
const ref=(order)=>`SHP-${order.reference}-${randomBytes(6).toString('hex')}`;
const view=(p)=>p&&({provider:p.provider,reference:p.providerReference,status:p.status,amountMinor:p.amountMinor,currency:p.currency,authorizationUrl:p.authorizationUrl,accessCode:p.accessCode,expiresAt:p.expiresAt});
export const initialize=async(patientId,orderId,key)=>{
 if(!adapter.configured())throw fail('CONFIG');
 const prepared=await r.transaction(async tx=>{if(!await r.patient(tx,patientId))throw fail('FORBIDDEN');const order=await r.order(tx,orderId,patientId);if(!order)throw fail('NOT_FOUND');if(order.reservation.expiresAt<=new Date())throw fail('EXPIRED');const old=await r.existing(tx,orderId,key);if(old)return {attempt:old,order};const created=await r.attempt(tx,{orderId,provider:'PAYSTACK',idempotencyKey:key,providerReference:ref(order),status:'PENDING',amountMinor:order.totalPayableMinor,currency:'NGN',expiresAt:order.reservation.expiresAt});return {attempt:created,order};});
 if(prepared.attempt.authorizationUrl)return {payment:view(prepared.attempt),idempotent:true};
 const result=await adapter.initialize({email:prepared.order.patient.email,amountMinor:prepared.order.totalPayableMinor,reference:prepared.attempt.providerReference});
 const attempt=await r.transaction(tx=>r.initialized(tx,prepared.attempt.id,{providerReference:result.reference,authorizationUrl:result.authorizationUrl,accessCode:result.accessCode})); return {payment:view(attempt),idempotent:false};
};
export const status=async(patientId,orderId)=>{const p=await r.paymentStatus(patientId,orderId);if(!p)throw fail('NOT_FOUND');return view(p)};
export const webhook=async(raw,event)=>r.transaction(async tx=>{const reference=event?.data?.reference;if(typeof reference!=='string'||!event?.event)throw fail('INVALID');const eventKey=createHash('sha256').update(raw).digest('hex');if(await r.event(tx,eventKey))return {duplicate:true};const attempt=await r.webhookAttempt(tx,reference);if(!attempt)throw fail('INVALID');if(event.data.amount!==attempt.amountMinor||event.data.currency!=='NGN')throw fail('INVALID');const success=event.event==='charge.success'&&event.data.status==='success';const failure=['charge.failed','charge.cancelled','charge.expired'].includes(event.event);if(!success&&!failure) {await r.eventCreate(tx,{paymentAttemptId:attempt.id,providerEventKey:eventKey,eventType:event.event,status:attempt.status});return {ignored:true};}if(success){if((await r.orderPaid(tx,attempt.orderId)).count){await r.paid(tx,attempt.id);await r.fulfilmentsPaid(tx,attempt.orderId);await r.audit(tx,attempt.order.patientId,'PAYMENT_SUCCEEDED',attempt.orderId);}await r.eventCreate(tx,{paymentAttemptId:attempt.id,providerEventKey:eventKey,eventType:event.event,status:'SUCCESS'});return {paid:true};}if((await r.orderFailed(tx,attempt.orderId)).count){await r.failed(tx,attempt.id,event.event==='charge.expired'?'EXPIRED':'FAILED');await r.fulfilmentsFailed(tx,attempt.orderId);if((await r.releaseReservation(tx,attempt.order.reservationId)).count)await Promise.all(attempt.order.reservation.allocations.map(a=>r.restore(tx,a.inventoryItemId,a.selectedQuantity)));await r.audit(tx,attempt.order.patientId,'PAYMENT_FAILED',attempt.orderId);}await r.eventCreate(tx,{paymentAttemptId:attempt.id,providerEventKey:eventKey,eventType:event.event,status:'FAILED'});return {failed:true};});
