import bcrypt from 'bcryptjs'; import prisma from '../../config/db.js';
const select = { id: true, userId: true, professionType: true, registrationNumber: true, practiceName: true, specialty: true, onboardingProgress: true, verificationStatus: true, decisionReason: true, decidedAt: true, createdAt: true };
const profileId = () => `#SHM${Math.floor(Math.random() * 100000).toString().padStart(5, '0')}`;
const audit = (tx, userId, type, professionalId) => tx.activityLog.create({ data: { userId, type, description: 'Professional verification state changed', meta: { professionalId } } });
export const register = async (data) => prisma.$transaction(async (tx) => { const user = await tx.user.create({ data: { patientId: profileId(), email: data.email, password: await bcrypt.hash(data.password, 12), full_name: data.fullName, phone_number: data.phoneNumber, roles: { create: { role: 'PROFESSIONAL' } } }, select: { id: true, email: true } }); const profile = await tx.professionalProfile.create({ data: { userId: user.id, professionType: data.professionType, registrationNumber: data.registrationNumber, practiceName: data.practiceName, specialty: data.specialty, onboardingProgress: 100 }, select }); await audit(tx, user.id, 'PROFESSIONAL_REGISTERED', profile.id); return profile; });
export const mine = (userId) => prisma.professionalProfile.findUnique({ where: { userId }, select });
export const isSuperAdmin = (userId) => prisma.userRole.findFirst({ where: { userId, role: 'SUPER_ADMIN' }, select: { id: true } });
export const list = async (q) => { const where = { ...(q.status ? { verificationStatus: q.status } : {}), ...(q.professionType ? { professionType: q.professionType } : {}) }; const [items, total] = await Promise.all([prisma.professionalProfile.findMany({ where, select, orderBy: { createdAt: 'asc' }, skip: (q.page - 1) * q.limit, take: q.limit }), prisma.professionalProfile.count({ where })]); return { items, page: q.page, limit: q.limit, total }; };
export const decide = (adminId, id, status, reason) => prisma.$transaction(async (tx) => { const profile = await tx.professionalProfile.findUnique({ where: { id }, select }); if (!profile) throw Object.assign(new Error('Not found'), { code: 'NOT_FOUND' }); if (profile.userId === adminId) throw Object.assign(new Error('Self decision'), { code: 'SELF' }); const allowed = { VERIFIED: ['PENDING', 'REJECTED', 'SUSPENDED'], REJECTED: ['PENDING'], SUSPENDED: ['VERIFIED'], PENDING: ['SUSPENDED'] }; if (!allowed[status].includes(profile.verificationStatus)) throw Object.assign(new Error('Invalid transition'), { code: 'INVALID' }); const updated = await tx.professionalProfile.update({ where: { id }, data: { verificationStatus: status, decisionReason: reason ?? null, decidedByUserId: adminId, decidedAt: new Date() }, select }); await audit(tx, adminId, `PROFESSIONAL_${status}`, id); return updated; });
