CREATE TYPE "WellnessOfferingStatus" AS ENUM ('DRAFT','PUBLISHED','ARCHIVED');
CREATE TYPE "WellnessBookingStatus" AS ENUM ('PENDING','CONFIRMED','REJECTED','CANCELLED');
CREATE TABLE "wellness_providers" ("id" TEXT NOT NULL, "organisation_id" TEXT, "professional_id" TEXT, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "wellness_providers_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "wellness_providers_organisation_id_key" ON "wellness_providers"("organisation_id"); CREATE UNIQUE INDEX "wellness_providers_professional_id_key" ON "wellness_providers"("professional_id");
CREATE TABLE "wellness_offerings" ("id" TEXT NOT NULL, "provider_id" TEXT NOT NULL, "name" VARCHAR(160) NOT NULL, "category" VARCHAR(80) NOT NULL, "description" VARCHAR(500), "price_minor" INTEGER, "status" "WellnessOfferingStatus" NOT NULL DEFAULT 'DRAFT', "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "wellness_offerings_pkey" PRIMARY KEY ("id"));
CREATE INDEX "wellness_offerings_status_category_created_at_idx" ON "wellness_offerings"("status","category","created_at");
CREATE TABLE "wellness_bookings" ("id" TEXT NOT NULL, "patient_id" TEXT NOT NULL, "offering_id" TEXT NOT NULL, "status" "WellnessBookingStatus" NOT NULL DEFAULT 'PENDING', "requested_at" TIMESTAMP(3) NOT NULL, "context" VARCHAR(300), "decision_reason" VARCHAR(300), "decided_at" TIMESTAMP(3), "decided_by_user_id" TEXT, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "wellness_bookings_pkey" PRIMARY KEY ("id"));
CREATE INDEX "wellness_bookings_patient_id_created_at_idx" ON "wellness_bookings"("patient_id","created_at"); CREATE INDEX "wellness_bookings_offering_id_status_requested_at_idx" ON "wellness_bookings"("offering_id","status","requested_at");
ALTER TABLE "wellness_providers" ADD CONSTRAINT "wellness_providers_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisations"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "wellness_providers" ADD CONSTRAINT "wellness_providers_professional_id_fkey" FOREIGN KEY ("professional_id") REFERENCES "professional_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "wellness_offerings" ADD CONSTRAINT "wellness_offerings_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "wellness_providers"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "wellness_bookings" ADD CONSTRAINT "wellness_bookings_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "wellness_bookings" ADD CONSTRAINT "wellness_bookings_offering_id_fkey" FOREIGN KEY ("offering_id") REFERENCES "wellness_offerings"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
