CREATE TYPE "PharmacyStaffStatus" AS ENUM ('PENDING','ACTIVE','DECLINED','REVOKED');
CREATE TYPE "PrescriptionRequestStatus" AS ENUM ('REQUESTED','QUOTED','CANCELLED');
CREATE TYPE "PharmacyQuoteStatus" AS ENUM ('ISSUED','REPLACED','EXPIRED');
CREATE TABLE "pharmacy_staff_members" ("id" TEXT PRIMARY KEY,"pharmacy_id" TEXT NOT NULL,"pharmacist_user_id" TEXT NOT NULL,"status" "PharmacyStaffStatus" NOT NULL DEFAULT 'PENDING',"invited_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"accepted_at" TIMESTAMP(3));
CREATE TABLE "prescription_requests" ("id" TEXT PRIMARY KEY,"prescription_id" TEXT NOT NULL,"patient_id" TEXT NOT NULL,"pharmacy_id" TEXT NOT NULL,"status" "PrescriptionRequestStatus" NOT NULL DEFAULT 'REQUESTED',"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "pharmacy_quotes" ("id" TEXT PRIMARY KEY,"request_id" TEXT NOT NULL,"pharmacist_staff_id" TEXT NOT NULL,"revision" INTEGER NOT NULL DEFAULT 1,"status" "PharmacyQuoteStatus" NOT NULL DEFAULT 'ISSUED',"quote_expires_at" TIMESTAMP(3) NOT NULL,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "pharmacy_quote_items" ("id" TEXT PRIMARY KEY,"quote_id" TEXT NOT NULL,"prescription_item_id" TEXT NOT NULL,"required_quantity" INTEGER NOT NULL,"available_quantity" INTEGER NOT NULL,"unit_price_minor" INTEGER NOT NULL,"line_total_minor" INTEGER NOT NULL,"availability_status" TEXT NOT NULL,"estimated_fulfilment" TEXT NOT NULL,"pickup_available" BOOLEAN NOT NULL DEFAULT false,"delivery_available" BOOLEAN NOT NULL DEFAULT false);
CREATE UNIQUE INDEX "pharmacy_staff_members_pharmacy_id_pharmacist_user_id_key" ON "pharmacy_staff_members"("pharmacy_id","pharmacist_user_id"); CREATE UNIQUE INDEX "prescription_requests_prescription_id_pharmacy_id_key" ON "prescription_requests"("prescription_id","pharmacy_id"); CREATE UNIQUE INDEX "pharmacy_quotes_request_id_revision_key" ON "pharmacy_quotes"("request_id","revision");
ALTER TABLE "pharmacy_staff_members" ADD FOREIGN KEY ("pharmacy_id") REFERENCES "pharmacies"("id") ON DELETE CASCADE; ALTER TABLE "pharmacy_staff_members" ADD FOREIGN KEY ("pharmacist_user_id") REFERENCES "users"("id") ON DELETE CASCADE; ALTER TABLE "prescription_requests" ADD FOREIGN KEY ("prescription_id") REFERENCES "prescriptions"("id") ON DELETE CASCADE; ALTER TABLE "prescription_requests" ADD FOREIGN KEY ("patient_id") REFERENCES "users"("id") ON DELETE CASCADE; ALTER TABLE "prescription_requests" ADD FOREIGN KEY ("pharmacy_id") REFERENCES "pharmacies"("id") ON DELETE CASCADE; ALTER TABLE "pharmacy_quotes" ADD FOREIGN KEY ("request_id") REFERENCES "prescription_requests"("id") ON DELETE CASCADE; ALTER TABLE "pharmacy_quotes" ADD FOREIGN KEY ("pharmacist_staff_id") REFERENCES "pharmacy_staff_members"("id") ON DELETE RESTRICT; ALTER TABLE "pharmacy_quote_items" ADD FOREIGN KEY ("quote_id") REFERENCES "pharmacy_quotes"("id") ON DELETE CASCADE;
