import express from 'express';
import { protect } from '../../middleware/authMiddleware.js';
import { validate } from '../../middleware/validateMiddleware.js';
import { createLimiter } from '../../middleware/rateLimitMiddleware.js';
import * as schema from './organisations.validator.js';
import * as controller from './organisations.controller.js';
const router = express.Router();
router.post('/register', createLimiter({ kind: 'organisation-registration', max: 5 }), express.json({ limit: '21mb' }), validate(schema.registration), controller.register);
router.use(express.json({ limit: '16kb' }));
router.get('/mine', protect, validate(schema.mine), controller.mine);
router.get('/admin', protect, validate(schema.queue), controller.queue);
router.get('/admin/:id', protect, validate(schema.detail), controller.detail);
for (const action of ['approve', 'reject', 'suspend', 'reactivate']) router.post(`/admin/:id/${action}`, protect, validate(schema.decision), controller.decision(action));
router.get('/pharmacy-compliance/:id', protect, validate(schema.detail), controller.pharmacyDetail);
router.get('/submissions/:id/documents/:key', protect, validate(schema.download), controller.download);
router.get('/', validate(schema.publicList), controller.publicList);
router.get('/:id', validate(schema.detail), controller.publicDetail);
router.use(controller.errorHandler);
export default router;
