import fs from 'node:fs';
import path from 'node:path';
import YAML from 'yaml';

const tags = ['Auth','Profile','Dashboard','Notifications','Appointments','Medications','Vitals','Health Metrics','Medical Records','Medical Documents','Family Care','Caregivers','Professionals','Organisations','Hospitals','Hospital Enrollments','Hospital Appointments','Doctor Care','Prescriptions','Pharmacies','Inventory','Pharmacy Requests and Quotes','Reservations','Checkout Pricing','Orders','Payments','Fulfilments','Delivery','Wellness'];
const r = (method, route, tag, summary, options = {}) => ({ method, route, tag, summary, ...options });
const routes = [
  r('get','/api/health','Dashboard','Service health check',{public:true,description:'Database-independent liveness response.'}),
  r('post','/api/v1/auth/register/patient','Auth','Register a patient',{public:true,body:'PatientRegistration'}), r('post','/api/v1/auth/login','Auth','Log in',{public:true,body:'Login'}), r('post','/api/v1/auth/refresh','Auth','Refresh an access token',{public:true,body:'RefreshToken'}), r('post','/api/v1/auth/logout','Auth','Revoke a refresh token',{public:true,body:'RefreshToken'}), r('post','/api/v1/auth/password-reset/request','Auth','Request a password reset',{public:true,body:'Email'}), r('post','/api/v1/auth/password-reset/confirm','Auth','Confirm a password reset',{public:true,body:'PasswordReset'}), r('get','/api/v1/auth/me','Auth','Get the authenticated account'),
  r('post','/api/v1/auth/register/caregiver','Caregivers','Register a caregiver',{public:true,body:'CaregiverRegistration'}), r('get','/api/v1/caregivers/me','Caregivers','Get caregiver onboarding state'),
  r('get','/api/v1/profile','Profile','Get profile'), r('get','/api/v1/profile/emergency-summary','Profile','Get minimized emergency summary'), r('put','/api/v1/profile/update','Profile','Update profile and consent settings',{body:'ProfileUpdate'}), r('put','/api/v1/profile/security','Profile','Update two-factor preference',{body:'SecurityPreference'}), r('put','/api/v1/profile/security/change-password','Profile','Change password',{body:'PasswordChange'}), r('delete','/api/v1/profile/delete-account','Profile','Delete account',{body:'DeleteConfirmation'}),
  r('get','/api/v1/dashboard','Dashboard','Get patient dashboard'), r('get','/api/v1/dashboard/records-stats','Dashboard','Get record statistics'),
  r('get','/api/v1/notifications','Notifications','List notifications',{query:'page'}), r('patch','/api/v1/notifications/read-all','Notifications','Mark all notifications read'), r('patch','/api/v1/notifications/{id}/read','Notifications','Mark notification read'),
  r('get','/api/v1/appointments','Appointments','List appointments',{query:'page'}), r('post','/api/v1/appointments','Appointments','Create appointment',{body:'Appointment'}), r('get','/api/v1/appointments/{id}','Appointments','Get appointment'), r('patch','/api/v1/appointments/{id}','Appointments','Update appointment',{body:'AppointmentUpdate'}), r('delete','/api/v1/appointments/{id}','Appointments','Cancel appointment'),
  r('get','/api/v1/medications','Medications','List medications',{query:'page'}), r('post','/api/v1/medications','Medications','Create medication',{body:'Medication'}), r('get','/api/v1/medications/{id}','Medications','Get medication'), r('put','/api/v1/medications/{id}','Medications','Update medication',{body:'MedicationUpdate'}), r('patch','/api/v1/medications/{id}/taken','Medications','Set medication adherence',{body:'Adherence'}), r('delete','/api/v1/medications/{id}','Medications','Delete medication'),
  r('get','/api/v1/vitals','Vitals','List vitals',{query:'page'}), r('post','/api/v1/vitals','Vitals','Record a manual vital',{body:'Vital'}), r('get','/api/v1/health-metrics','Health Metrics','List stored health metrics',{query:'page'}),
  r('get','/api/v1/medical-records','Medical Records','List medical-record metadata',{query:'page'}), r('post','/api/v1/medical-records','Medical Records','Create medical-record metadata',{body:'MedicalRecord'}), r('get','/api/v1/medical-records/timeline','Medical Records','List record timeline',{query:'page'}), r('get','/api/v1/medical-records/uncategorized','Medical Records','List uncategorized records',{query:'page'}), r('get','/api/v1/medical-records/emergency-summary','Medical Records','Get approved emergency summary fields'), r('get','/api/v1/medical-records/categories','Medical Records','List record categories'), r('post','/api/v1/medical-records/categories','Medical Records','Create record category',{body:'RecordCategory'}), r('get','/api/v1/medical-records/categories/counts','Medical Records','Get category counts'), r('patch','/api/v1/medical-records/categories/{id}','Medical Records','Update record category',{body:'RecordCategoryUpdate'}), r('delete','/api/v1/medical-records/categories/{id}','Medical Records','Delete empty record category'), r('get','/api/v1/medical-records/{id}','Medical Records','Get medical-record metadata'), r('patch','/api/v1/medical-records/{id}','Medical Records','Update medical-record metadata',{body:'MedicalRecordUpdate'}), r('delete','/api/v1/medical-records/{id}','Medical Records','Delete medical-record metadata'), r('patch','/api/v1/medical-records/{id}/category','Medical Records','Assign a record category',{body:'CategoryAssignment'}),
  r('post','/api/v1/medical-documents/uploads','Medical Documents','Initialize a private direct upload',{body:'DocumentUpload',response:'DocumentUploadResponse',description:'Patient owner only. Returns a short-lived signed PUT URL for private quarantine storage. The URL is ephemeral and must never be persisted as document data. Missing R2 configuration returns DOCUMENT_STORAGE_UNAVAILABLE (503).'}), r('post','/api/v1/medical-documents/{id}/complete-upload','Medical Documents','Confirm direct upload completion',{description:'Owner only. Verifies private object metadata and changes PENDING_UPLOAD to PENDING_SCAN; it does not claim the file is clean.'}), r('get','/api/v1/medical-documents','Medical Documents','List owned documents',{query:'document',response:'DocumentListResponse',description:'Owner-scoped metadata only; no signed or public URLs.'}), r('get','/api/v1/medical-documents/{id}','Medical Documents','Get owned document metadata',{response:'DocumentResponse',description:'Owner-scoped metadata only; no signed or public URL.'}), r('post','/api/v1/medical-documents/{id}/download','Medical Documents','Authorize owner download',{response:'SignedDownloadResponse',description:'Owner only and CLEAN documents only. The signed GET URL is short-lived and is never persisted.'}), r('post','/api/v1/medical-documents/{id}/shares','Medical Documents','Grant a named document share',{body:'DocumentShare',description:'Owner grants an expiring share only to an eligible active doctor or a family caregiver with RECORDS permission. This is not a public bearer link.'}), r('post','/api/v1/medical-documents/{id}/shares/{shareId}/revoke','Medical Documents','Revoke a named document share'), r('get','/api/v1/medical-documents/shared-with-me','Medical Documents','List active named shares',{query:'page'}), r('post','/api/v1/medical-documents/shared-with-me/{shareId}/download','Medical Documents','Authorize recipient download',{response:'SignedDownloadResponse',description:'Authenticated named recipient only; grant must be active and unexpired and document must be CLEAN.'}), r('delete','/api/v1/medical-documents/{id}','Medical Documents','Soft-delete a document and revoke access'), r('get','/api/v1/medical-documents/emergency-summary.pdf','Medical Documents','Download owner emergency-summary PDF',{pdf:true,description:'Patient owner only. Generated in memory from approved emergency-summary fields; never stored in R2.'}),
  r('get','/api/v1/family-care','Family Care','List care relationships',{query:'page'}), r('post','/api/v1/family-care/invitations','Family Care','Invite a caregiver',{body:'CareInvitation'}), r('post','/api/v1/family-care/invitations/accept','Family Care','Accept invitation',{body:'InvitationToken'}), r('post','/api/v1/family-care/invitations/decline','Family Care','Decline invitation',{body:'InvitationToken'}), r('patch','/api/v1/family-care/{id}/permissions','Family Care','Update caregiver permissions',{body:'Permissions'}), r('delete','/api/v1/family-care/{id}','Family Care','Revoke care relationship'), r('get','/api/v1/family-care/access/{patientId}','Family Care','Get explicit caregiver permissions'), r('get','/api/v1/family-care/circle','Family Care','Get patient-owned care circle'), r('post','/api/v1/family-care/members','Family Care','Add or invite a circle member',{body:'CircleMember'}), r('get','/api/v1/family-care/members/{id}','Family Care','Get circle member'), r('delete','/api/v1/family-care/members/{id}','Family Care','Remove circle member'), r('post','/api/v1/family-care/members/{id}/approve','Family Care','Approve join request',{body:'Permissions'}), r('post','/api/v1/family-care/join-links','Family Care','Create expiring join link',{body:'PermissionLevel'}), r('post','/api/v1/family-care/join/lookup','Family Care','Look up join request',{body:'JoinToken'}), r('post','/api/v1/family-care/join','Family Care','Request to join circle',{body:'JoinRequest'}), r('post','/api/v1/family-care/dependents','Family Care','Create owned dependent',{body:'Dependent'}), r('get','/api/v1/family-care/dependents/{id}','Family Care','Get owned dependent or permitted caregiver view',{description:'Owners can read owned dependents. Caregivers receive only the explicit permission-based read access implemented by the service.'}), r('patch','/api/v1/family-care/dependents/{id}','Family Care','Update owned dependent',{body:'DependentUpdate',description:'Owner only; caregiver access is read-only where implemented.'}), r('delete','/api/v1/family-care/dependents/{id}','Family Care','Delete owned dependent',{description:'Owner only.'}), r('get','/api/v1/family-care/calendar','Family Care','Read permission-scoped care calendar',{query:'calendar'}), r('get','/api/v1/family-care/calendar/upcoming','Family Care','Read upcoming care-calendar items',{query:'calendar'}),
  r('post','/api/v1/professionals/register','Professionals','Register a professional',{public:true,body:'ProfessionalRegistration'}), r('get','/api/v1/professionals/me','Professionals','Get professional status'), r('get','/api/v1/professionals/admin','Professionals','List professionals for Super Admin',{query:'page'}), ...['approve','reject','suspend','reactivate'].map((a)=>r('post',`/api/v1/professionals/admin/{id}/${a}`,'Professionals',`${a[0].toUpperCase()+a.slice(1)} professional`,{body:'Decision'})),
  r('post','/api/v1/organisations/register','Organisations','Register an organisation',{public:true,body:'OrganisationRegistration'}), r('get','/api/v1/organisations/mine','Organisations','Get owned organisation'), r('get','/api/v1/organisations/admin','Organisations','List organisation submissions for Super Admin',{query:'page'}), r('get','/api/v1/organisations/admin/{id}','Organisations','Get organisation submission for Super Admin'), ...['approve','reject','suspend','reactivate'].map((a)=>r('post',`/api/v1/organisations/admin/{id}/${a}`,'Organisations',`${a[0].toUpperCase()+a.slice(1)} organisation`,{body:'Decision'})), r('get','/api/v1/organisations/pharmacy-compliance/{id}','Organisations','Get pharmacy compliance detail'), r('get','/api/v1/organisations/submissions/{id}/documents/{key}','Organisations','Download private onboarding evidence'), r('get','/api/v1/organisations','Organisations','List verified organisations',{public:true,query:'page'}), r('get','/api/v1/organisations/{id}','Organisations','Get verified organisation',{public:true}),
  r('get','/api/v1/hospitals/{hospitalId}/plans','Hospitals','List active hospital plans',{public:true,query:'offset'}), r('get','/api/v1/hospitals/{hospitalId}/plans/{planId}','Hospitals','Get active hospital plan',{public:true}), r('get','/api/v1/hospitals/{hospitalId}/plans/manage','Hospitals','List managed hospital plans',{query:'offset'}), r('post','/api/v1/hospitals/{hospitalId}/plans','Hospitals','Create hospital plan',{body:'HospitalPlan'}), r('patch','/api/v1/hospitals/{hospitalId}/plans/{planId}','Hospitals','Update hospital plan',{body:'HospitalPlanUpdate'}), r('post','/api/v1/hospitals/{hospitalId}/plans/{planId}/archive','Hospitals','Archive hospital plan'),
  r('post','/api/v1/hospital-enrollments','Hospital Enrollments','Request hospital enrollment',{body:'HospitalEnrollment',description:'Patient owner may enroll self or an owned dependent. New enrollment is PENDING.'}), r('get','/api/v1/hospital-enrollments/mine','Hospital Enrollments','List patient enrollments',{query:'offset'}), r('get','/api/v1/hospital-enrollments/hospital','Hospital Enrollments','List hospital enrollment queue',{query:'offset'}), r('get','/api/v1/hospital-enrollments/{id}','Hospital Enrollments','Get authorized enrollment'), r('post','/api/v1/hospital-enrollments/{id}/approve','Hospital Enrollments','Approve pending enrollment',{description:'Authorized hospital operator changes PENDING to ACTIVE.'}), r('post','/api/v1/hospital-enrollments/{id}/reject','Hospital Enrollments','Reject pending enrollment',{body:'Rejection',description:'Authorized hospital operator changes PENDING to REJECTED.'}),
  r('post','/api/v1/hospital-appointments','Hospital Appointments','Request hospital appointment',{body:'HospitalAppointment',description:'Patient owner may request for self or an owned dependent. Initial state is PENDING.'}), r('get','/api/v1/hospital-appointments/mine','Hospital Appointments','List patient hospital appointments',{query:'offset'}), r('get','/api/v1/hospital-appointments/hospital','Hospital Appointments','List hospital appointment queue',{query:'offset'}), r('get','/api/v1/hospital-appointments/{id}','Hospital Appointments','Get authorized hospital appointment'), r('post','/api/v1/hospital-appointments/{id}/confirm','Hospital Appointments','Schedule pending appointment',{description:'Authorized hospital operator changes PENDING to SCHEDULED.'}), r('post','/api/v1/hospital-appointments/{id}/reject','Hospital Appointments','Reject pending appointment',{body:'Rejection'}), r('post','/api/v1/hospital-appointments/{id}/check-in','Hospital Appointments','Check in scheduled appointment',{description:'Authorized hospital operator changes SCHEDULED to CHECKED_IN.'}),
  r('get','/api/v1/doctor-care/doctors','Doctor Care','List verified doctors',{query:'page'}), r('get','/api/v1/doctor-care/doctors/{id}','Doctor Care','Get verified doctor'), r('post','/api/v1/doctor-care/relationships','Doctor Care','Request doctor-care relationship',{body:'DoctorCareRequest'}), r('get','/api/v1/doctor-care/relationships/patient','Doctor Care','List patient doctor relationships'), r('get','/api/v1/doctor-care/relationships/doctor','Doctor Care','List doctor patient relationships'), r('post','/api/v1/doctor-care/relationships/{id}/accept','Doctor Care','Accept doctor-care request'), r('post','/api/v1/doctor-care/relationships/{id}/decline','Doctor Care','Decline doctor-care request'), r('delete','/api/v1/doctor-care/relationships/{id}','Doctor Care','Revoke doctor-care relationship'),
  r('get','/api/v1/prescriptions/patient','Prescriptions','List patient prescriptions',{query:'page'}), r('get','/api/v1/prescriptions/issued','Prescriptions','List doctor-issued prescriptions',{query:'page'}), r('post','/api/v1/prescriptions','Prescriptions','Create prescription draft',{body:'PrescriptionDraft'}), r('put','/api/v1/prescriptions/{id}','Prescriptions','Update prescription draft',{body:'PrescriptionDraftUpdate'}), r('post','/api/v1/prescriptions/{id}/issue','Prescriptions','Issue prescription'), r('delete','/api/v1/prescriptions/{id}','Prescriptions','Cancel prescription'), r('get','/api/v1/prescriptions/{id}','Prescriptions','Get authorized prescription'),
  r('post','/api/v1/pharmacies/register','Pharmacies','Register pharmacy',{public:true,body:'PharmacyRegistration'}), r('get','/api/v1/pharmacies','Pharmacies','List verified pharmacies',{public:true,query:'page'}), r('get','/api/v1/pharmacies/{id}','Pharmacies','Get verified pharmacy',{public:true}), r('get','/api/v1/pharmacies/compliance','Pharmacies','List pharmacies for compliance admin',{query:'page'}), r('get','/api/v1/pharmacies/mine','Pharmacies','Get administered pharmacy'), r('post','/api/v1/pharmacies/compliance/{id}/decision','Pharmacies','Record compliance decision',{body:'PharmacyDecision'}),
  r('post','/api/v1/inventory','Inventory','Create pharmacy inventory item',{body:'InventoryItem'}), r('get','/api/v1/inventory','Inventory','List pharmacy inventory',{query:'page'}), r('put','/api/v1/inventory/{id}','Inventory','Update pharmacy inventory item',{body:'InventoryItemUpdate'}), r('delete','/api/v1/inventory/{id}','Inventory','Deactivate pharmacy inventory item'), r('get','/api/v1/pharmacies/discovery/prescriptions/{id}','Inventory','Discover inventory for prescription',{query:'discovery'}),
  r('post','/api/v1/pharmacy-requests/staff/invite','Pharmacy Requests and Quotes','Invite pharmacy staff',{body:'StaffInvite'}), r('post','/api/v1/pharmacy-requests/staff/{id}/accept','Pharmacy Requests and Quotes','Accept pharmacy staff invitation'), r('post','/api/v1/pharmacy-requests','Pharmacy Requests and Quotes','Send prescription requests to pharmacies',{body:'PharmacyRequests'}), r('get','/api/v1/pharmacy-requests/patient','Pharmacy Requests and Quotes','List patient pharmacy requests',{query:'page'}), r('get','/api/v1/pharmacy-requests/pharmacy','Pharmacy Requests and Quotes','List pharmacy request queue',{query:'page'}), r('post','/api/v1/pharmacy-requests/{id}/quotes','Pharmacy Requests and Quotes','Submit pharmacy quote',{body:'PharmacyQuote'}), r('get','/api/v1/pharmacy-requests/quotes/patient','Pharmacy Requests and Quotes','List patient quotes',{query:'page'}),
  r('post','/api/v1/reservations','Reservations','Create inventory reservation',{body:'Reservation'}), r('get','/api/v1/reservations/active','Reservations','Get active reservation'), r('get','/api/v1/reservations/{id}','Reservations','Get owned reservation'), r('delete','/api/v1/reservations/{id}','Reservations','Release reservation'),
  r('get','/api/v1/checkout-pricing/admin','Checkout Pricing','Get current pricing configuration'), r('put','/api/v1/checkout-pricing/admin','Checkout Pricing','Update pricing configuration',{body:'PricingConfig'}), r('post','/api/v1/checkout-pricing/preview/reservations/{id}','Checkout Pricing','Preview reservation checkout',{body:'CheckoutPreview'}),
  r('post','/api/v1/orders','Orders','Create order from reservation',{body:'Order'}), r('get','/api/v1/orders','Orders','List owned orders'), r('get','/api/v1/orders/{id}','Orders','Get owned order'),
  r('post','/api/v1/orders/{id}/payment/initialize','Payments','Initialize Paystack payment',{body:'PaymentInitialize',description:'Patient action. Amount and order ownership are server controlled; the returned Paystack authorization URL is temporary.'}), r('get','/api/v1/orders/{id}/payment','Payments','Get payment status'), r('post','/api/v1/payments/paystack/webhook','Payments','Receive Paystack webhook',{public:true,body:'PaystackWebhook',description:'Server/provider-facing endpoint authenticated by Paystack signature verification. It is not a frontend action.'}),
  r('get','/api/v1/fulfilments','Fulfilments','List pharmacist fulfilment queue'), r('get','/api/v1/fulfilments/{id}','Fulfilments','Get fulfilment detail'), r('post','/api/v1/fulfilments/{id}/decision','Fulfilments','Record pharmacist decision',{body:'FulfilmentDecision'}), r('post','/api/v1/fulfilments/{id}/preparation','Fulfilments','Advance preparation state',{body:'PreparationTransition'}),
  r('put','/api/v1/delivery/operations/partners/{id}','Delivery','Configure delivery partner',{body:'DeliveryPartner'}), r('get','/api/v1/delivery/partners','Delivery','List delivery partners',{query:'offset'}), r('post','/api/v1/delivery/fulfilments/{id}/assignment','Delivery','Assign delivery partner',{body:'DeliveryAssignment'}), r('get','/api/v1/delivery/assignments','Delivery','List delivery assignment queue',{query:'offset'}), r('get','/api/v1/delivery/assignments/{id}','Delivery','Get delivery assignment'), r('post','/api/v1/delivery/assignments/{id}/accept','Delivery','Accept delivery assignment'), r('post','/api/v1/delivery/assignments/{id}/reject','Delivery','Reject delivery assignment',{body:'Rejection'}), r('post','/api/v1/delivery/assignments/{id}/status','Delivery','Advance delivery status',{body:'DeliveryTransition'}), r('post','/api/v1/delivery/assignments/{id}/locations','Delivery','Record delivery location',{body:'Coordinates'}), r('get','/api/v1/delivery/orders/{id}/tracking','Delivery','Get authorized order tracking'),
  r('get','/api/v1/wellness','Wellness','List wellness offerings',{public:true,query:'offset'}), r('get','/api/v1/wellness/{id}','Wellness','Get wellness offering',{public:true}), r('post','/api/v1/wellness/bookings','Wellness','Create wellness booking',{body:'WellnessBooking',description:'Authenticated patient creates a PENDING booking.'}), r('get','/api/v1/wellness/bookings/mine','Wellness','List patient wellness bookings',{query:'offset'}), r('get','/api/v1/wellness/bookings/provider','Wellness','List provider wellness queue',{query:'offset'}), r('get','/api/v1/wellness/bookings/{id}','Wellness','Get authorized wellness booking'), r('post','/api/v1/wellness/bookings/{id}/confirm','Wellness','Confirm pending wellness booking',{body:'Decision',description:'Authorized provider changes PENDING to CONFIRMED.'}), r('post','/api/v1/wellness/bookings/{id}/reject','Wellness','Reject pending wellness booking',{body:'Decision',description:'Authorized provider changes PENDING to REJECTED.'}),
];

const string = { type: 'string' }, uuid = { type: 'string', format: 'uuid' }, dateTime = { type: 'string', format: 'date-time' };
const obj = (properties, required = Object.keys(properties)) => ({ type: 'object', additionalProperties: false, properties, ...(required.length ? { required } : {}) });
const enumString = (...values) => ({ type: 'string', enum: values });
const schemas = {
  Error: obj({ status: { const: 'error' }, message: string, code: string }, ['status','message']),
  Success: obj({ status: { const: 'success' }, data: {} }, ['status']),
  PatientRegistration: obj({ email: { type:'string',format:'email',maxLength:320 }, password: { type:'string',format:'password',minLength:8,maxLength:128 }, firstName:{type:'string',maxLength:100}, lastName:{type:'string',maxLength:100}, phoneNumber:{type:'string',minLength:7,maxLength:30}, dateOfBirth:{type:'string',format:'date'}, gender:{type:'string',maxLength:50}, consentGiven:{const:true} }, ['email','password','firstName','lastName','consentGiven']),
  Login: obj({ email:{type:'string',format:'email'}, password:{type:'string',format:'password'} }), RefreshToken: obj({ refreshToken:string }), Email: obj({ email:{type:'string',format:'email'} }), PasswordReset: obj({ uid:uuid,token:string,password:{type:'string',format:'password',minLength:8},confirmPassword:{type:'string',format:'password'} }),
  CaregiverRegistration: obj({ account:obj({firstName:string,lastName:string,email:{type:'string',format:'email'},phone:string,dateOfBirth:{type:'string',format:'date'},country:enumString('Nigeria','Ghana','Kenya','South Africa','United Kingdom','United States','Other'),state:string,city:string,password:{type:'string',format:'password'},confirmPassword:{type:'string',format:'password'}}),caregiverType:enumString('Parent','Guardian','Spouse','Child','Sibling','Relative','Professional caregiver','Legal representative','Other'),connection:{oneOf:[obj({mode:{const:'invite'},relationship:string,inviteContact:string}),obj({mode:{const:'connect'},relationship:string,patientReference:string})]},consent:obj({terms:{const:true},privacy:{const:true}}) }),
  ProfileUpdate: { type:'object',additionalProperties:false,properties:{ full_name:string,phone_number:string,email:{type:'string',format:'email'},dob:{type:['string','null'],format:'date'},blood_type:enumString('A+','A-','B+','B-','AB+','AB-','O+','O-'),genotype:enumString('AA','AS','SS','AC','SC'),chronic_conditions:string,known_allergies:string,current_medications:string,smoking_status:string,alcohol_frequency:string,physical_activity:string,appointment_reminders:{type:'boolean'},prescription_alerts:{type:'boolean'},health_tips_newsletter:{type:'boolean'},data_sharing_consent:{type:'boolean'},electronic_health_records:{type:'boolean'},emergency_access_permissions:{type:'array',items:string},emergencyContactName:string,emergencyContactPhone:string,emergencyContactRelation:string,gender:string } },
  SecurityPreference: obj({ two_factor_auth:{type:'boolean'} }), PasswordChange: obj({ current_password:{type:'string',format:'password'},new_password:{type:'string',format:'password'} }), DeleteConfirmation: obj({ confirmation:{const:'DELETE'} }),
  Appointment: obj({ title:{type:'string',minLength:2,maxLength:120},doctorName:{type:'string',minLength:2,maxLength:120},time:dateTime,type:enumString('IN_PERSON','VIRTUAL') }, ['title','time','type']), AppointmentUpdate:{type:'object',additionalProperties:false,properties:{title:string,doctorName:{type:['string','null']},time:dateTime,type:enumString('IN_PERSON','VIRTUAL')}},
  Medication: obj({ name:string,instructions:string,time:string }), MedicationUpdate:{type:'object',additionalProperties:false,properties:{name:string,instructions:string,time:string}}, Adherence:obj({isTaken:{type:'boolean'}}),
  Vital: obj({type:enumString('BLOOD_PRESSURE','HEART_RATE','TEMPERATURE','BLOOD_GLUCOSE','OXYGEN_SATURATION'),unit:string,value:{oneOf:[{type:'number'},obj({systolic:{type:'number'},diastolic:{type:'number'}})]},status:enumString('NORMAL','LOW','HIGH','UNSPECIFIED'),recordedAt:dateTime}),
  MedicalRecord: obj({title:string,recordType:enumString('PHYSICAL','VIRTUAL','LAB_RESULT','IMAGING','OTHER'),date:dateTime,categoryId:{...uuid,type:['string','null']},doctorName:string,facility:string,diagnosis:string,treatment:string,notes:string,documentUrl:string},['title','recordType','date']), MedicalRecordUpdate:{type:'object',additionalProperties:false,properties:{title:string,recordType:string,date:dateTime,categoryId:{type:['string','null'],format:'uuid'},doctorName:string,facility:string,diagnosis:string,treatment:string,notes:string,documentUrl:string}}, RecordCategory:obj({name:string,icon:enumString('folder','stethoscope','flask','scan','syringe','pill','hospital'),isDefault:{type:'boolean'}},['name','icon']),RecordCategoryUpdate:{type:'object',additionalProperties:false,properties:{name:string,icon:string}},CategoryAssignment:obj({categoryId:{type:['string','null'],format:'uuid'}}),
  DocumentStatus: enumString('PENDING_UPLOAD','PENDING_SCAN','CLEAN','INFECTED','REJECTED','PENDING_CLINICAL_REVIEW','DELETED'), DocumentUpload:obj({filename:{type:'string',maxLength:180},contentType:enumString('application/pdf','image/jpeg','image/png'),byteSize:{type:'integer',minimum:1,maximum:10485760},kind:enumString('MEDICAL_RECORD','LAB_RESULT','IMAGING','EXTERNAL_PRESCRIPTION','OTHER'),medicalRecordId:uuid},['filename','contentType','byteSize','kind']), DocumentShare:obj({recipientId:uuid,expiresAt:dateTime}), MedicalDocument:{type:'object',additionalProperties:false,properties:{id:uuid,originalFilename:string,declaredContentType:string,validatedContentType:{type:['string','null']},byteSize:{type:'integer'},kind:string,status:{$ref:'#/components/schemas/DocumentStatus'},medicalRecordId:{type:['string','null'],format:'uuid'},scanVerdict:{type:['string','null'],enum:['CLEAN','INFECTED','REJECTED',null]},scanRequestedAt:{type:['string','null'],format:'date-time'},scannedAt:{type:['string','null'],format:'date-time'},sha256:{type:['string','null']},createdAt:dateTime,updatedAt:dateTime,deletedAt:{type:['string','null'],format:'date-time'}},required:['id','originalFilename','declaredContentType','byteSize','kind','status']},
  DocumentResponse:obj({status:{const:'success'},data:{$ref:'#/components/schemas/MedicalDocument'}}), DocumentListResponse:obj({status:{const:'success'},data:obj({items:{type:'array',items:{$ref:'#/components/schemas/MedicalDocument'}},page:{type:'integer'},limit:{type:'integer'},total:{type:'integer'}})}), DocumentUploadResponse:obj({status:{const:'success'},data:obj({document:{$ref:'#/components/schemas/MedicalDocument'},upload:obj({method:{const:'PUT'},url:{type:'string',format:'uri',description:'Ephemeral signed URL; never persist.'},expiresInSeconds:{type:'integer'},headers:{type:'object',additionalProperties:{type:'string'}}})})}),SignedDownloadResponse:obj({status:{const:'success'},data:obj({url:{type:'string',format:'uri',description:'Ephemeral signed URL; never persist.'},expiresInSeconds:{type:'integer'}})}),
  CareInvitation:obj({email:{type:'string',format:'email'},relationshipType:enumString('CAREGIVER','DEPENDENT'),permissions:{type:'array',items:enumString('PROFILE','RECORDS','APPOINTMENTS','MEDICATIONS','VITALS','EMERGENCY_SUMMARY')},expiresAt:dateTime}),InvitationToken:obj({token:string}),Permissions:obj({permissions:{type:'array',items:enumString('PROFILE','RECORDS','APPOINTMENTS','MEDICATIONS','VITALS','EMERGENCY_SUMMARY')}}),PermissionLevel:obj({permissionLevel:enumString('owner','care-manager','caregiver','viewer','emergency-only')}),JoinToken:obj({token:string}),JoinRequest:obj({token:string,permissionLevel:enumString('owner','care-manager','caregiver','viewer','emergency-only'),requestedPermissions:{type:'array',items:string}}),CircleMember:{type:'object',additionalProperties:false,properties:{method:enumString('email','patientId'),email:{type:'string',format:'email'},patientReference:string,relationship:string,permissions:{type:'array',items:string},permissionLevel:string},required:['method','relationship','permissions','permissionLevel']},Dependent:{type:'object',additionalProperties:false,properties:{fullName:string,dateOfBirth:{type:'string',format:'date'},gender:enumString('Male','Female'),bloodGroup:enumString('A+','A-','B+','B-','O+'),genotype:enumString('AA','AS','SS','AC','SC'),allergies:{type:'array',items:string},conditions:{type:'array',items:string},careType:enumString('Child','Elderly'),immunizationStatus:enumString('Up to date','Partially complete','Not started'),milestones:{type:'array',items:string}},required:['fullName','dateOfBirth']},DependentUpdate:{type:'object',additionalProperties:false,properties:{fullName:string,dateOfBirth:{type:'string',format:'date'},gender:string,bloodGroup:string,genotype:string,allergies:{type:'array',items:string},conditions:{type:'array',items:string},careType:string,immunizationStatus:string,milestones:{type:'array',items:string}}},
  ProfessionalRegistration:obj({email:{type:'string',format:'email'},password:{type:'string',format:'password'},fullName:string,phoneNumber:string,professionType:enumString('DOCTOR','NURSE','DENTIST','DERMATOLOGIST','PSYCHIATRIST','PSYCHOLOGIST','PHYSIOTHERAPIST','PHARMACIST','NUTRITIONIST_DIETITIAN','OPTOMETRIST','MIDWIFE','OTHER_HEALTHCARE_PROFESSIONAL'),registrationNumber:string,practiceName:string,specialty:string},['email','password','fullName','phoneNumber','professionType','registrationNumber']),Decision:{type:'object',additionalProperties:false,properties:{reason:string}},OrganisationRegistration:obj({organisationType:enumString('hospital','clinic','pharmacy','laboratory','diagnostic-centre','other'),organisation:obj({entityName:string,legalName:string,country:enumString('Nigeria','Ghana','Kenya','South Africa','United Kingdom','United States','Other'),state:string,city:string,address:string,phone:string,email:{type:'string',format:'email'},website:{type:'string',format:'uri'}},['entityName','legalName','country','state','city','address','phone','email']),representative:obj({firstName:string,lastName:string,phone:string,email:{type:'string',format:'email'},position:string,password:{type:'string',format:'password'},confirmPassword:{type:'string',format:'password'}}),regulatory:obj({registrationNumber:string,regulatoryAuthority:string}),documents:obj({businessRegistration:{$ref:'#/components/schemas/OrganisationDocument'},representativeId:{$ref:'#/components/schemas/OrganisationDocument'},facilityLicense:{$ref:'#/components/schemas/OrganisationDocument'},pharmacyLicense:{$ref:'#/components/schemas/OrganisationDocument'}},['businessRegistration','representativeId']),services:{type:'array',items:string},operatingInfo:obj({openingHours:string,delivery:{type:'boolean'},pickup:{type:'boolean'}},[]),consent:obj({terms:{const:true},privacy:{const:true},healthData:{type:'boolean'}},['terms','privacy'])}),OrganisationDocument:obj({name:string,contentType:enumString('application/pdf','image/jpeg','image/png'),base64:{type:'string',contentEncoding:'base64'}}),
  HospitalPlan:obj({name:string,description:{type:['string','null']},feeMinor:{type:'integer',minimum:0,description:'NGN minor units (kobo).'}},['name','feeMinor']),HospitalPlanUpdate:{type:'object',additionalProperties:false,properties:{name:string,description:{type:['string','null']},feeMinor:{type:'integer',minimum:0,description:'NGN minor units (kobo).'}}},HospitalEnrollment:obj({hospitalId:uuid,planId:uuid,dependentId:uuid,patientNote:string},['hospitalId','planId']),Rejection:{type:'object',additionalProperties:false,properties:{reason:string}},HospitalAppointment:obj({hospitalId:uuid,dependentId:uuid,requestedAt:dateTime,appointmentType:string,reason:string},['hospitalId','requestedAt']),DoctorCareRequest:obj({doctorProfileId:uuid}),
  PrescriptionItem:obj({medicationName:string,dosage:string,frequency:enumString('ONCE_DAILY','TWICE_DAILY','THREE_TIMES_DAILY','FOUR_TIMES_DAILY','EVERY_4_HOURS','EVERY_6_HOURS','EVERY_8_HOURS','EVERY_12_HOURS','AS_NEEDED','OTHER'),route:enumString('ORAL','TOPICAL','INHALATION','SUBCUTANEOUS','INTRAMUSCULAR','INTRAVENOUS','RECTAL','OPHTHALMIC','OTIC','NASAL','OTHER'),duration:string,quantity:{type:'integer'},indication:string}),PrescriptionDraft:obj({patientId:uuid,instructions:string,items:{type:'array',items:{$ref:'#/components/schemas/PrescriptionItem'}}},['patientId','items']),PrescriptionDraftUpdate:{type:'object',additionalProperties:false,properties:{instructions:string,items:{type:'array',items:{$ref:'#/components/schemas/PrescriptionItem'}}}},
  PharmacyRegistration:obj({email:{type:'string',format:'email'},password:{type:'string',format:'password'},name:string,address:string,country:string,state:string,city:string,contactEmail:{type:'string',format:'email'},contactPhone:string,latitude:{type:'number'},longitude:{type:'number'}},['email','password','name','address','country','state','city','contactEmail','contactPhone']),PharmacyDecision:obj({status:enumString('VERIFIED','REJECTED','SUSPENDED'),note:string},['status']),InventoryItem:obj({medicationName:string,genericName:string,availableQuantity:{type:'integer'},unitPriceMinor:{type:'integer',description:'NGN minor units (kobo).'},currency:{const:'NGN'}},['medicationName','availableQuantity','unitPriceMinor']),InventoryItemUpdate:{type:'object',additionalProperties:false,properties:{medicationName:string,genericName:string,availableQuantity:{type:'integer'},unitPriceMinor:{type:'integer',description:'NGN minor units (kobo).'},isActive:{type:'boolean'}}},
  StaffInvite:obj({pharmacistUserId:uuid}),
  PharmacyRequests:obj({prescriptionId:uuid,pharmacyIds:{type:'array',items:uuid,minItems:1}}),
  PharmacyQuote: obj({
    items: {
      type: 'array',
      items: obj({
        prescriptionItemId: uuid,
        inventoryItemId: uuid,
        requiredQuantity: { type: 'integer' },
        availableQuantity: { type: 'integer' },
        unitPriceMinor: { type: 'integer', description: 'NGN minor units (kobo).' },
        availabilityStatus: enumString('AVAILABLE','PARTIAL','UNAVAILABLE'),
        estimatedFulfilment: string,
        pickupAvailable: { type: 'boolean' },
        deliveryAvailable: { type: 'boolean' },
      }),
    },
  }),
  Reservation:obj({prescriptionId:uuid,idempotencyKey:string,allocations:{type:'array',items:obj({prescriptionItemId:uuid,quoteItemId:uuid,selectedQuantity:{type:'integer'}})}}),
  Coordinates:obj({latitude:{type:'number',minimum:-90,maximum:90},longitude:{type:'number',minimum:-180,maximum:180}}),PricingConfig:obj({platformFeeMinor:{type:'integer',description:'NGN minor units (kobo).'},deliveryRatePerKmMinor:{type:'integer',description:'NGN minor units (kobo).'},currency:{const:'NGN'}}),CheckoutPreview:obj({fulfilments:{type:'array',items:obj({pharmacyId:uuid,fulfilmentMethod:enumString('PICKUP','DELIVERY')})},deliveryCoordinates:{$ref:'#/components/schemas/Coordinates'}},['fulfilments']),Order:obj({reservationId:uuid,idempotencyKey:string,fulfilments:{type:'array',items:obj({pharmacyId:uuid,fulfilmentMethod:enumString('PICKUP','DELIVERY')})},delivery:obj({recipientName:string,recipientPhone:string,address:string,coordinates:{$ref:'#/components/schemas/Coordinates'}})},['reservationId','idempotencyKey','fulfilments']),PaymentInitialize:obj({idempotencyKey:string}),PaystackWebhook:{type:'object',description:'Provider payload. Frontends must never call this endpoint.',additionalProperties:true},
  FulfilmentDecision:obj({decision:enumString('APPROVED_FOR_DISPENSING','CLARIFICATION_REQUIRED','REJECTED','UNABLE_TO_FULFILL'),note:string,patientMessage:string},['decision','note']),PreparationTransition:obj({transition:enumString('PREPARING','READY_FOR_PICKUP')}),DeliveryPartner:obj({displayName:string,isActive:{type:'boolean'}}),DeliveryAssignment:obj({partnerId:uuid}),DeliveryTransition:obj({status:enumString('PICKED_UP','OUT_FOR_DELIVERY','DELIVERED')}),WellnessBooking:obj({offeringId:uuid,requestedAt:dateTime,context:string},['offeringId','requestedAt']),
};

const querySets = {
  page:[['page',{type:'integer',minimum:1}],['limit',{type:'integer',minimum:1,maximum:100}]], offset:[['limit',{type:'integer',minimum:1,maximum:100}],['offset',{type:'integer',minimum:0}]], document:[['page',{type:'integer',minimum:1}],['limit',{type:'integer',minimum:1,maximum:50}],['kind',{$ref:'#/components/schemas/DocumentUpload/properties/kind'}],['status',{$ref:'#/components/schemas/DocumentStatus'}]], calendar:[['patientId',uuid],['dependentId',uuid],['from',dateTime],['to',dateTime]], discovery:[['latitude',{type:'number'}],['longitude',{type:'number'}],['radiusKm',{type:'number',maximum:100}],['page',{type:'integer'}],['limit',{type:'integer'}]],
};
const createdPaths = new Set(['/api/v1/auth/register/patient','/api/v1/auth/register/caregiver','/api/v1/professionals/register','/api/v1/organisations/register','/api/v1/pharmacies/register','/api/v1/appointments','/api/v1/medications','/api/v1/vitals','/api/v1/medical-records','/api/v1/medical-records/categories','/api/v1/medical-documents/uploads','/api/v1/medical-documents/{id}/shares','/api/v1/family-care/members','/api/v1/family-care/join-links','/api/v1/family-care/dependents','/api/v1/hospitals/{hospitalId}/plans','/api/v1/hospital-enrollments','/api/v1/hospital-appointments','/api/v1/prescriptions','/api/v1/inventory','/api/v1/pharmacy-requests','/api/v1/reservations','/api/v1/orders','/api/v1/wellness/bookings']);
const noContentPaths = new Set(['/api/v1/medical-documents/{id}/shares/{shareId}/revoke','/api/v1/medical-documents/{id}']);
const storagePaths = new Set(['post /api/v1/medical-documents/uploads','post /api/v1/medical-documents/{id}/complete-upload','post /api/v1/medical-documents/{id}/download','post /api/v1/medical-documents/shared-with-me/{shareId}/download','delete /api/v1/medical-documents/{id}']);
const responses = (route) => {
  const successCode = noContentPaths.has(route.route) && (route.method === 'delete' || route.route.includes('/revoke')) ? '204' : createdPaths.has(route.route) && route.method === 'post' ? '201' : '200';
  const success = route.pdf ? {description:'PDF response',content:{'application/pdf':{schema:{type:'string',contentEncoding:'binary'}}}} : successCode === '204' ? {description:'Operation completed; no response body'} : {description:'Successful response',content:{'application/json':{schema:{$ref:`#/components/schemas/${route.response || 'Success'}`}}}};
  const result = {[successCode]:success};
  if (route.body || route.query || route.route.includes('{')) result['400'] = {$ref:'#/components/responses/BadRequest'};
  if (!route.public) result['401'] = {$ref:'#/components/responses/Unauthorized'};
  if (route.route.includes('{') || route.description?.toLowerCase().includes('owner')) result['404'] = {$ref:'#/components/responses/NotFound'};
  if (route.method !== 'get') result['409'] = {$ref:'#/components/responses/Conflict'};
  result['429'] = {$ref:'#/components/responses/RateLimited'};
  result['500'] = {$ref:'#/components/responses/ServerError'};
  if (storagePaths.has(`${route.method} ${route.route}`)) result['503'] = {$ref:'#/components/responses/StorageUnavailable'};
  return result;
};
const paths = {};
for (const route of routes) {
  const parameters = [...route.route.matchAll(/\{([^}]+)\}/g)].map(([,name])=>({name,in:'path',required:true,schema:name==='key'?{type:'string',maxLength:100}:uuid}));
  for (const [name,schema] of querySets[route.query] || []) parameters.push({name,in:'query',required:false,schema});
  const operation = { tags:[route.tag],summary:route.summary,description:route.description,operationId:`${route.method}_${route.route.replace(/[^a-zA-Z0-9]+/g,'_')}`,security:route.public?[]:[{bearerAuth:[]}],...(parameters.length?{parameters}:{}),...(route.body?{requestBody:{required:true,content:{'application/json':{schema:{$ref:`#/components/schemas/${route.body}`}}}}}:{}),responses:responses(route) };
  paths[route.route] ||= {}; paths[route.route][route.method] = Object.fromEntries(Object.entries(operation).filter(([,v])=>v!==undefined));
}
const response = (description) => ({description,content:{'application/json':{schema:{$ref:'#/components/schemas/Error'}}}});
const document = { openapi:'3.1.0',info:{title:'Sabi Health Backend API',version:'1.0.0',license:{name:'Proprietary',identifier:'LicenseRef-Proprietary'},description:'Canonical frontend and operations reference generated from the registered Express routes and validation contracts. All currency values ending in Minor are NGN minor units (kobo).'},servers:[{url:'/',description:'Current environment'}],tags:tags.map((name)=>({name,description:`${name} endpoints currently registered by the backend.`})),paths,components:{securitySchemes:{bearerAuth:{type:'http',scheme:'bearer',bearerFormat:'JWT',description:'Use an access token. Example: Bearer <access-token>'}},schemas,responses:{BadRequest:response('Invalid request'),Unauthorized:response('Authentication required or token invalid'),NotFound:response('Resource is absent or hidden by authorization scope'),Conflict:response('State conflict'),RateLimited:response('Rate limit exceeded'),ServerError:response('Safe module-scoped server error'),StorageUnavailable:{description:'Private document storage is not configured or available',content:{'application/json':{schema:{$ref:'#/components/schemas/Error'},example:{status:'error',code:'DOCUMENT_STORAGE_UNAVAILABLE',message:'Document storage is unavailable'}}}}}}};
fs.writeFileSync(path.resolve('docs/openapi.yaml'), YAML.stringify(document,{lineWidth:0,aliasDuplicateObjects:false}));
console.log(`Wrote docs/openapi.yaml with ${routes.length} operations across ${tags.length} tags.`);
