import express from 'express'; import { protect } from '../../middleware/authMiddleware.js'; import { validate } from '../../middleware/validateMiddleware.js'; import * as V from './family-care.validator.js'; import * as C from './family-care.controller.js';
import { createLimiter } from '../../middleware/rateLimitMiddleware.js';
import * as Calendar from './family-care.calendar.controller.js';
import * as CalendarSchema from './family-care.calendar.validator.js';
const router = express.Router(); router.use(protect);
router.get('/calendar', validate(CalendarSchema.calendar), Calendar.calendar);
router.get('/calendar/upcoming', validate(CalendarSchema.upcoming), Calendar.upcoming);
router.all('/calendar', Calendar.readOnly);
router.all('/calendar/upcoming', Calendar.readOnly);
const joinLimiter = createLimiter({ kind: 'family-join', max: 20 });
router.get('/circle', validate(V.circleSchema), C.circle);
router.post('/members', validate(V.addMemberSchema), C.addMember);
router.get('/members/:id', validate(V.memberSchema), C.member);
router.delete('/members/:id', validate(V.memberSchema), C.removeMember);
router.post('/members/:id/approve', validate(V.approveSchema), C.approve);
router.post('/join-links', validate(V.linkSchema), C.createLink);
router.post('/join/lookup', joinLimiter, validate(V.lookupSchema), C.lookup);
router.post('/join', joinLimiter, validate(V.joinSchema), C.join);
router.post('/dependents', validate(V.createDependentSchema), C.createDependent);
router.get('/dependents/:id', validate(V.memberSchema), C.dependent);
router.patch('/dependents/:id', validate(V.updateDependentSchema), C.updateDependent);
router.delete('/dependents/:id', validate(V.memberSchema), C.removeDependent);
router.get('/', validate(V.listSchema), C.list); router.post('/invitations', validate(V.inviteSchema), C.invite); router.post('/invitations/accept', validate(V.tokenSchema), C.accept); router.post('/invitations/decline', validate(V.tokenSchema), C.decline); router.get('/access/:patientId', validate(V.accessSchema), C.access); router.patch('/:id/permissions', validate(V.permissionsSchema), C.permissions); router.delete('/:id', validate(V.relationshipId), C.revoke);
router.use((err, req, res, next) => res.status(500).json({ status: 'error', message: 'Family care module temporarily unavailable' })); export default router;
